spring:         
    # HTTP ENCODING  
    http:  
        encoding.charset: UTF-8  
        encoding.enable: true  
        encoding.force: true  
        multipart.maxFileSize: 10000Mb
        multipart.maxRequestSize: 10000Mb
    datasource:  
        url: jdbc:mysql://localhost:3306/filesystem?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 1
        driver-class-name: com.mysql.jdbc.Driver 

    #thymeleaf start
    thymeleaf:
        prefix: classpath:/templates/
        mode: LEGACYHTML5
        encoding: UTF-8
        content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
        cache: false
    #thymeleaf end
    
    

mybatis:
    mapper-locations: classpath*:mapper/*.xml  
    type-aliases-package: com.fxy.bean    
            
            
#配置日志
logging:
  #配置日志文件路径
  level:
    #xatu.zsl: debug #不同目录下的日志可配置不同级别
    #org.springfromework.web: info
    #org.hibernate: error
    com.fxy.dao: DEBUG  
  #采用相对路径方式将日志文件输出到【log\myspringboot.log】
  file: log\myspringboot.log
  
  

  
  
  
  
  
  
 

    